name: deploy-prod

on:
  push:
    branches:
      - prod

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: PROD  # 👈 This is critical. Do NOT use "github-pages"
      url: https://feruzurazaliev.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload built site
        uses: actions/upload-pages-artifact@v2  # ✅ upgraded version

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
