name: pr-to-prod

on:
  push:
    branches:
      - uat

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: uat
          destination_branch: prod
          pr_title: "Promote UAT to PROD"
          pr_body: "This is an automated pull request promoting the latest build to production."
          github_token: ${{ secrets.GITHUB_TOKEN }}
